version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-api-dev
    ports:
      - "5000:5000"
    volumes:
      # Monta o código fonte para hot reload
      - .:/app
      # Volume para evitar conflitos com node_modules se existir
      - /app/__pycache__
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    # Reinicia automaticamente se o container parar
    restart: unless-stopped
    # Comando para desenvolvimento com reload automático
    command: python app.py
    # Healthcheck para verificar se a aplicação está funcionando
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
